In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("ForeignGifts_edu.csv")
df.head()

,ID,OPEID,Institution Name,City,State,Foreign Gift Received Date,Foreign Gift Amount,Gift Type,Country of Giftor,Giftor Name
0,1,102000,Jacksonville State University,Jacksonville,AL,43738,250000,Monetary Gift,CHINA,NaN
1,2,104700,Troy University,Troy,AL,43592,463657,Contract,CHINA,Confucius Institute Headquarters
2,3,105100,University of Alabama,Tuscaloosa,AL,43466,3649107,Contract,ENGLAND,Springer Nature Customer Service Ce
3,4,105100,University of Alabama,Tuscaloosa,AL,43472,1000,Contract,SAUDI ARABIA,Saudi Arabia Education Mission
4,5,105100,University of Alabama,Tuscaloosa,AL,43479,49476,Contract,SAUDI ARABIA,Saudi Arabia Education Mission

In [2]:
print(df["Gift Type"].value_counts())

Gift Type
Contract         17274
Monetary Gift    10936
Real Estate         11
Name: count, dtype: int64

In [3]:
print(df.groupby("Gift Type")["Foreign Gift Amount"].describe())

                 count          mean           std       min       25%  \
Gift Type
Contract       17274.0  6.257945e+05  3.768217e+06 -537770.0   13757.5
Monetary Gift  10936.0  5.281504e+05  2.086487e+06       1.0     250.0
Real Estate       11.0  1.335265e+06  1.412071e+06   39456.0  370574.5

                    50%        75%         max
Gift Type
Contract       110000.0   366000.0  99999999.0
Monetary Gift   50000.0   400000.0  48842186.0
Real Estate    667555.0  2121736.0   4312000.0

The three types of gifts are Contract, Monetary Gift, and Real Estate. Contract is the most common type of gift at roughly 17000, versus Monetary Gift at 10000 and Real Estate at only 11. Contracts also had a larger median at $110,000 versus Monetary Gifts with a median of $50,000. Real Estate gifts were rare but very large, with a median around $668,000.

Q1: Which Country Gives the most money in total?

In [5]:
df.groupby("Country of Giftor")["Foreign Gift Amount"].sum().nlargest(10)

Country of Giftor
QATAR           2706240869
ENGLAND         1464906771
CHINA           1237952112
SAUDI ARABIA    1065205930
BERMUDA          899593972
CANADA           898160656
HONG KONG        887402529
JAPAN            655954776
SWITZERLAND      619899445
INDIA            539556490
Name: Foreign Gift Amount, dtype: int64

Answer: Qatar

Q2: Which country initiates the most gifts, by count?

In [6]:
df["Country of Giftor"].value_counts().head(10)

Country of Giftor
ENGLAND         3655
CHINA           2461
CANADA          2344
JAPAN           1896
SWITZERLAND     1676
SAUDI ARABIA    1610
FRANCE          1437
GERMANY         1394
HONG KONG       1080
SOUTH KOREA      811
Name: count, dtype: int64

Answer: England

Q3: Which country gives the largest gifts, on average?

In [7]:
df.groupby("Country of Giftor")["Foreign Gift Amount"].mean().nlargest(10)

Country of Giftor
BERMUDA     7.688837e+06
ECUADOR     3.985140e+06
QATAR       3.905109e+06
ANTIGUA     3.435545e+06
JERSEY      3.064589e+06
MOROCCO     2.740214e+06
RUSSIA      2.025462e+06
GUERNSEY    1.750000e+06
IRAQ        1.665520e+06
CYPRUS      1.562512e+06
Name: Foreign Gift Amount, dtype: float64

Answer: Bermuda, Ecuador, Qatar, however Ecuador only has a few gifts in total given versus the other top countries.

Q4: Which institution receive the most money, in total?

In [8]:
df.groupby("Institution Name")["Foreign Gift Amount"].sum().nlargest(10)

Institution Name
Carnegie Mellon University               1477922504
Cornell University                       1289937761
Harvard University                        954803610
Massachusetts Institute of Technology     859071692
Yale University                           613441311
Texas A&M University                      521455050
Johns Hopkins University                  502409595
Northwestern University                   402316221
Georgetown University                     379950511
University of Chicago (The)               364544338
Name: Foreign Gift Amount, dtype: int64

Answer: Carnegie Mellon

Q5: Which institution receive the greatest number of gifts, by count?

In [9]:
df["Institution Name"].value_counts().head(10)

Institution Name
University of California, Los Angeles          3916
California Institute of Technology             2502
Columbia University in the City of New York    1127
Ohio State University (The)                    1014
Johns Hopkins University                        899
University of Michigan - Ann Arbor              715
Stanford University                             668
Cornell University                              653
University of Pennsylvania                      625
Massachusetts Institute of Technology           582
Name: count, dtype: int64

Answer: UCLA

Q6: What is the average amount each university receives? Median amount? If they are different why?

In [13]:
univ_stats = df.groupby("Institution Name")["Foreign Gift Amount"].agg(["sum", "mean", "median","count"])

In [14]:
univ_stats.sort_values("sum", ascending=False).head(10)

,sum,mean,median,count
Institution Name,,,,
Carnegie Mellon University,1477922504,8.256550e+06,747776.0,179
Cornell University,1289937761,1.975402e+06,250000.0,653
Harvard University,954803610,2.107734e+06,893120.0,453
Massachusetts Institute of Technology,859071692,1.476068e+06,500000.0,582
Yale University,613441311,1.115348e+06,510967.0,550
Texas A&M University,521455050,1.386849e+06,165854.5,376
Johns Hopkins University,502409595,5.588538e+05,110145.0,899
Northwestern University,402316221,1.602853e+06,267497.0,251
Georgetown University,379950511,3.917016e+06,500000.0,97
University of Chicago (The),364544338,9.090881e+05,381165.0,401

In [16]:
df["Foreign Gift Amount"].mean()

np.float64(588232.7172672832)

In [17]:
df["Foreign Gift Amount"].median()

np.float64(94615.0)

Q7: What is the largest flow of a single country to a single institution?

In [18]:
df.groupby(["Country of Giftor", "Institution Name"])["Foreign Gift Amount"].sum().nlargest(10)

Country of Giftor     Institution Name
QATAR                 Cornell University                1018473315
BERMUDA               Carnegie Mellon University         750000000
QATAR                 Texas A&M University               504099350
                      Carnegie Mellon University         425410702
                      Georgetown University              327128310
                      Northwestern University            311148564
CANADA                Brigham Young University           259927758
UNITED ARAB EMIRATES  University of Colorado Boulder     219734835
ENGLAND               Harvard University                 188328288
HONG KONG             Yale University                    161131218
Name: Foreign Gift Amount, dtype: int64

Answer: Qatar -> Cornell University

Q8: Which are the top giftors to US academic institutions?

In [19]:
df["Giftor Name"].value_counts().head(15)

Giftor Name
Saudi Arabian Cultural Mission         480
Human Frontier Science Program         287
Anonymous                              262
Qatar Foundation                       261
Novartis Pharmaceuticals Corp          251
Royal Embassy of Saudi Arabia          210
Acerta Pharma B.V.                     210
Contracting Party                      143
Gwangju Institute of S&T               141
WSB Universities                       140
Qatar National Research Fund           124
Shire Human Genetics Therapies, Inc    108
RiMED Foundation                       106
Novartis                               105
Boehringer Ingelheim Pharmaceutical    104
Name: count, dtype: int64

Answer: Saudi Arabian Cultural Mission, Human Frontier Sceicne Program, Anonymous Gifts, Qatar Foundation